### PR TITLE
mod compat with pga

### PR DESCRIPTION
**Pull request by AbsolemJackdaw**
Hi ! I contacted you recently about compatibility.
I have now overthrown the system, so any mod could add compatibility in a simple json located in assets/modid/load_screens
I went ahead and made the file for you, so you would just have to merge it 

I'm going to PR the 4 images that come along with this as well !
Here's a guide on how these work ; 
https://github.com/ArtixAllMighty/PublicGuiAnnouncement/wiki/Add-Mod-Compatibility

If you have any questions or remarks, please do let me know ! 
best regards,
Absolem

### CODE REVIEW

**Comment by AbsolemJackdaw** [comment]
for any information on how this json file works, you can visit 
https://github.com/ArtixAllMighty/PublicGuiAnnouncement/wiki/Add-Mod-Compatibility

**Comment by MrTroble** [comment]
So you want to add customization to this mod? In form of this json data ?
Idk how this system should work out and also this is up to @HyCraftHD to decide whether this will be implemented or not. What is this system exactly for and what else do we have to implement?

**Comment by HyCraftHD** [comment]
Hello @ArtixAllMighty. I really like the mod idea.
I have two questions (or concerns)
- The music player mod is client only, so does your mod even work? Have you tested it?
- The json file is small enough, so that could easily be merged.
- In #27 you tried to submit images but there were no images but only links. I don't know if they are downloaded on request then but if so, I don't really like the idea because of security and privacy concerns. If the files should be included in this mod they should be reasonably small, cause the file size of a release of music player mod is already quite large.

Just wanna hear your thoughts on this.
~Johannes

**Comment by AbsolemJackdaw** [comment]
* even though your mod is client only, my own mod loads the json files client side only too. The information contained in this folder is send torugh my own packets across the server. The only interaction your mod has in this compatibility file, is the paths written out as strings, both for the class and texture file  
* great ! 
* yes I tried to submit images. markdown doesnt work on files, and I haven't found out how to submit pictures just trough browser. i think i'm going to have to use the fork and open it in my IDE to add the images for a decent PR. The files are small. they are all 426x240, and 400kb each. If you find this to be to big, you can downscale them, and adjust the sizes in the json file. 

answering to mr troble : 
apart from my PR, not anything really.   
if you happen to change a class path , you'll need to change it in the json too.  
if you happen to add any other screens, you may want to add an entry for PGA to load up a tiny screen when opening your gui. 

how does the system work ?  
PGA gives a personal list of entries to each individual player (client side) that are loaded trough json. 
a map of ClassName linked with TexturePath. the string form of the path is used.  
whenever a player opens a container or gui screen, a forge event is fired, and PGA will check the map for any corresponding entries from the class path of the opened container or gui. if an entry exist, a simple LayerRenderer will show the mapped texture in front of the players face. 
the only thing you might need to implement apart from the json and a texture is nothing.   
PGA loads any json out of assets/anymodid/load_screens  
the texture can be literally anywhere. you just need to give the correct path in the json.  

My first approach for the textures is generally just using the simple provided textures by the mod. it doesnt have to be super fancy.  
But in your case, the mod doesnt have a gui texture file, it is composed in-game directly, So I just take a snap of the picture, and scale it down.  

If you guys have any other questions, feel free to ask !

**Comment by AbsolemJackdaw** [comment]
the code is open source if you want to know the fine details

https://github.com/ArtixAllMighty/PublicGuiAnnouncement  

also, HyCraftHD : no, you dont need to load it trough link. i really didnt find a quicker solution to show you guys the images. if you dont want to download them yourself and add them, i understand, and i'll try to make a decent pr. apologies for the confusion

**Comment by AbsolemJackdaw** [comment]
closing this issue as i will be starting a correct PR , with image files included !

**Comment by HyCraftHD** [comment]
Okay, perfect!

**Comment by AbsolemJackdaw** [comment]
full pr now available in #28

**Pull request closed without merging**
